// <auto-generated />
using System;
using BTB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(BTBContext))]
    partial class BTBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BTB.Entities.Models.Nodo", b =>
                {
                    b.Property<byte>("IdNodo")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int?>("DuenoNodoId")
                        .HasColumnType("int");

                    b.Property<string>("PartidaIdPartida")
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdNodo");

                    b.HasIndex("DuenoNodoId");

                    b.HasIndex("PartidaIdPartida");

                    b.ToTable("Nodo");
                });

            modelBuilder.Entity("BTB.Entities.Models.Partida", b =>
                {
                    b.Property<string>("IdPartida")
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdPartida");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("BTB.Entities.Models.Tier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTier");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasDefaultValue(new DateTime(2026, 2, 15, 22, 12, 12, 651, DateTimeKind.Local).AddTicks(6623));

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tiers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaCreacion = new DateTime(2026, 2, 15, 22, 12, 12, 651, DateTimeKind.Local).AddTicks(6270),
                            Titulo = "Bronce"
                        },
                        new
                        {
                            Id = 2,
                            FechaCreacion = new DateTime(2026, 2, 15, 22, 12, 12, 651, DateTimeKind.Local).AddTicks(6273),
                            Titulo = "Plata"
                        },
                        new
                        {
                            Id = 3,
                            FechaCreacion = new DateTime(2026, 2, 15, 22, 12, 12, 651, DateTimeKind.Local).AddTicks(6275),
                            Titulo = "Oro"
                        });
                });

            modelBuilder.Entity("BTB.Entities.Models.Tropa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("Damage")
                        .HasColumnType("float");

                    b.Property<byte?>("NodoIdNodo")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Vida")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("NodoIdNodo");

                    b.ToTable("Tropa");
                });

            modelBuilder.Entity("BTB.Entities.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Usuario_Tier")
                        .HasColumnType("int");

                    b.Property<bool>("Visible")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("Usuario_Tier");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PartidaUsuario", b =>
                {
                    b.Property<int>("ArrUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("LstPartidasIdPartida")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ArrUsuarioId", "LstPartidasIdPartida");

                    b.HasIndex("LstPartidasIdPartida");

                    b.ToTable("PartidaUsuario");
                });

            modelBuilder.Entity("BTB.Entities.Models.Nodo", b =>
                {
                    b.HasOne("BTB.Entities.Models.Usuario", "DuenoNodo")
                        .WithMany()
                        .HasForeignKey("DuenoNodoId");

                    b.HasOne("BTB.Entities.Models.Partida", null)
                        .WithMany("LstNodos")
                        .HasForeignKey("PartidaIdPartida");

                    b.Navigation("DuenoNodo");
                });

            modelBuilder.Entity("BTB.Entities.Models.Tropa", b =>
                {
                    b.HasOne("BTB.Entities.Models.Nodo", null)
                        .WithMany("ArrTropas")
                        .HasForeignKey("NodoIdNodo");
                });

            modelBuilder.Entity("BTB.Entities.Models.Usuario", b =>
                {
                    b.HasOne("BTB.Entities.Models.Tier", "Tier")
                        .WithMany("LstUsuarios")
                        .HasForeignKey("Usuario_Tier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("PartidaUsuario", b =>
                {
                    b.HasOne("BTB.Entities.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ArrUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BTB.Entities.Models.Partida", null)
                        .WithMany()
                        .HasForeignKey("LstPartidasIdPartida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BTB.Entities.Models.Nodo", b =>
                {
                    b.Navigation("ArrTropas");
                });

            modelBuilder.Entity("BTB.Entities.Models.Partida", b =>
                {
                    b.Navigation("LstNodos");
                });

            modelBuilder.Entity("BTB.Entities.Models.Tier", b =>
                {
                    b.Navigation("LstUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
