// <auto-generated />
using System;
using BTB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(BTBContext))]
    partial class BTBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BTB.Entities.Models.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte>("NodoDestinoIdNodo")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("PartidaIdPartida")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TropaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NodoDestinoIdNodo");

                    b.HasIndex("PartidaIdPartida");

                    b.HasIndex("TropaId");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("BTB.Entities.Models.Nodo", b =>
                {
                    b.Property<byte>("IdNodo")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int?>("DuenoNodoUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("PartidaIdPartida")
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdNodo");

                    b.HasIndex("DuenoNodoUsuarioId");

                    b.HasIndex("PartidaIdPartida");

                    b.ToTable("Nodos");

                    b.HasData(
                        new
                        {
                            IdNodo = (byte)1
                        },
                        new
                        {
                            IdNodo = (byte)2
                        },
                        new
                        {
                            IdNodo = (byte)3
                        });
                });

            modelBuilder.Entity("BTB.Entities.Models.Partida", b =>
                {
                    b.Property<string>("IdPartida")
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdPartida");

                    b.ToTable("Partidas");

                    b.HasData(
                        new
                        {
                            IdPartida = "partida-001"
                        },
                        new
                        {
                            IdPartida = "partida-002"
                        });
                });

            modelBuilder.Entity("BTB.Entities.Models.Tier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tiers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaCreacion = new DateTime(2026, 3, 6, 2, 31, 54, 781, DateTimeKind.Local).AddTicks(9197),
                            Titulo = "Bronce"
                        },
                        new
                        {
                            Id = 2,
                            FechaCreacion = new DateTime(2026, 3, 6, 2, 31, 54, 781, DateTimeKind.Local).AddTicks(9245),
                            Titulo = "Plata"
                        },
                        new
                        {
                            Id = 3,
                            FechaCreacion = new DateTime(2026, 3, 6, 2, 31, 54, 781, DateTimeKind.Local).AddTicks(9246),
                            Titulo = "Oro"
                        });
                });

            modelBuilder.Entity("BTB.Entities.Models.Tropa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("Damage")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Vida")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Tropas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Damage = 50f,
                            Nombre = "Triangulo",
                            Vida = 100f
                        },
                        new
                        {
                            Id = 2,
                            Damage = 50f,
                            Nombre = "Cuadrado",
                            Vida = 100f
                        },
                        new
                        {
                            Id = 3,
                            Damage = 50f,
                            Nombre = "Circulo",
                            Vida = 100f
                        });
                });

            modelBuilder.Entity("BTB.Entities.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("Visible")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("TierId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Correo = "Jhon@gmail.com",
                            FechaCreacion = new DateTime(2026, 3, 6, 2, 31, 54, 782, DateTimeKind.Local).AddTicks(7691),
                            Nombre = "Ejemplo",
                            Password = "asd",
                            Rol = "Admin",
                            TierId = 1,
                            Visible = true
                        },
                        new
                        {
                            UsuarioId = 2,
                            Correo = "Mary@gmail.com",
                            FechaCreacion = new DateTime(2026, 3, 6, 2, 31, 54, 782, DateTimeKind.Local).AddTicks(7703),
                            Nombre = "Ejemplo2",
                            Password = "asdasd",
                            Rol = "Admin",
                            TierId = 1,
                            Visible = true
                        },
                        new
                        {
                            UsuarioId = 3,
                            Correo = "player1@gmail.com",
                            FechaCreacion = new DateTime(2026, 3, 6, 2, 31, 54, 782, DateTimeKind.Local).AddTicks(7704),
                            Nombre = "Player1",
                            Password = "pass123",
                            Rol = "Usuario",
                            TierId = 2,
                            Visible = true
                        },
                        new
                        {
                            UsuarioId = 4,
                            Correo = "player2@gmail.com",
                            FechaCreacion = new DateTime(2026, 3, 6, 2, 31, 54, 782, DateTimeKind.Local).AddTicks(7704),
                            Nombre = "Player2",
                            Password = "pass456",
                            Rol = "Usuario",
                            TierId = 3,
                            Visible = true
                        });
                });

            modelBuilder.Entity("UsuarioPartida", b =>
                {
                    b.Property<int>("ArrUsuarioUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("PartidasIdPartida")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ArrUsuarioUsuarioId", "PartidasIdPartida");

                    b.HasIndex("PartidasIdPartida");

                    b.ToTable("UsuarioPartida");
                });

            modelBuilder.Entity("BTB.Entities.Models.Movimiento", b =>
                {
                    b.HasOne("BTB.Entities.Models.Nodo", "NodoDestino")
                        .WithMany()
                        .HasForeignKey("NodoDestinoIdNodo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BTB.Entities.Models.Partida", "Partida")
                        .WithMany("movimientos")
                        .HasForeignKey("PartidaIdPartida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BTB.Entities.Models.Tropa", "Tropa")
                        .WithMany()
                        .HasForeignKey("TropaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NodoDestino");

                    b.Navigation("Partida");

                    b.Navigation("Tropa");
                });

            modelBuilder.Entity("BTB.Entities.Models.Nodo", b =>
                {
                    b.HasOne("BTB.Entities.Models.Usuario", "DuenoNodo")
                        .WithMany()
                        .HasForeignKey("DuenoNodoUsuarioId");

                    b.HasOne("BTB.Entities.Models.Partida", null)
                        .WithMany("LstNodos")
                        .HasForeignKey("PartidaIdPartida");

                    b.Navigation("DuenoNodo");
                });

            modelBuilder.Entity("BTB.Entities.Models.Usuario", b =>
                {
                    b.HasOne("BTB.Entities.Models.Tier", "Tier")
                        .WithMany("UsuarioId")
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("UsuarioPartida", b =>
                {
                    b.HasOne("BTB.Entities.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ArrUsuarioUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BTB.Entities.Models.Partida", null)
                        .WithMany()
                        .HasForeignKey("PartidasIdPartida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BTB.Entities.Models.Partida", b =>
                {
                    b.Navigation("LstNodos");

                    b.Navigation("movimientos");
                });

            modelBuilder.Entity("BTB.Entities.Models.Tier", b =>
                {
                    b.Navigation("UsuarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
